### Register User
POST http://localhost:3000/v1/api/account/signup
Content-Type: application/json

{
  "username": "DannyBrai",
  "password": "TheFlashsucksnow%2018"
}

### Log in User
POST http://localhost:3000/v1/api/account/login
Content-Type: application/json

{
  "username": "DannyBrai",
  "password": "TheFlashsucksnow%2018"
}

### Log out User
GET http://localhost:3000/account/logout

### Atomize a Long URL
POST http://localhost:3000/v1/api/data/atomize
Content-Type: application/json

{
  "longUrl": "https://github.com/goforprodev"
}

### Visit an Atomized URL
GET http://localhost:3000/g7YEe


